name: BetterRespawn
main: me.theredcat.betterespawn.Main
authors: [TheRedCat,MaxThe777]
version: 1.0
depend: [HolographicDisplays]
api-version: 1.16
commands:
  respawninstant:
    description: Instantly respawns player if is dead.